### ISSUE TITLE
test_SRMR fails when it calls for the 'preprocess' function

### ISSUE THREAD

**Issue by wangxiaobaobao** [MuSAELab/SRMRToolbox#2]
Undefined the 'char' type of input parameters corresponding to the function 'preprocess'.

error in SRMR (line 38)
[s, fs] = preprocess(s, fs);

error in  test_SRMR (line 6)
[ratio, energy] = SRMR(file);

**Comment by jfsantos** [comment]
Have you added the directory `libs` to the MATLAB path before running the tests? Try this, from inside the `SRMRToolbox` directory:

```MATLAB
addpath(genpath('libs'));
addpath('test');
test_SRMR
```

The function `preprocess` in this repository supports both the `preprocess(filename)` and `preprocess(s, fs)` syntaxes, so the code is correct. If the code above does not work for you, you could have another function called `preprocess` in your MATLAB path which conflicts with SRMRToolbox.

**Comment by wangxiaobaobao** [comment]
It is ok now, thank you very much!
